### PR TITLE
Fix a few device quirks

### PR DESCRIPTION
**Pull request by ximion**
Hi!
This is a follow-up on https://github.com/Aharoni-Lab/Miniscope-DAQ-QT-Software/pull/4
I was investigating why the Miniscope software wasn't working on Linux, going through the layers of OpenCV -> v4l-libs -> kernel driver -> firmware and found out that there were two issues with the device:
 * The device was advertising to support more stream controls than it actually could, resulting in the driver invalidating a whole block of controls (gamma, saturation, sharpness), likely due to heuristics meant to work around faulty hardware. The first patch in this series fixes that, advertising only actually supported controls in `bmControls`
 * The device was attempting to return *unsigned* integers for which the USB UVC specification requires *signed* integers, namely for HUE and BRIGHTNESS. Since `0xFFFF` is -1 in signed-int form, the system assumes a max value of -1 and a minimum value of 0. The driver performs value sanitization, clamping the sent values to their min/max range before the device sees them, so any value submitted by an application will be lost (same applies to values sent *from* the device) I have no idea why this particular issue isn't seen on Windows, apparently that OS is very forgiving.

With these patches applied, I get zero warnings from the kernel when the device is plugged in. I can write all control values and read the same values back from the device. I can also watch the correct values being transferred when intercepting USB communication.
And yet for some reason the LED intensity on my v3 Miniscope still doesn't change. I have never tested this on Windows, so there is a chance that the v3 support doesn't fully work on any platform. I will have to verify that somehow and then test again. Or maybe someone else has an idea what else could be wrong here (I haven't yet figured out how to debug the device itself while it's running).

In any case, these patches should already be helpful to some extent, and definitely resolve some issues on Linux.
Thanks for considering!
Cheers,
    Matthias

P.S: I had to resist the urge to clean up the repository (that -metadata folder should likley go into .gitignore) and fix the typo in the source folder name ^^

### CODE REVIEW

**Comment by daharoni** [comment]
Thanks for looking into all of this @ximion! I'll test these changes out with a Miniscope connected to a Window's machine. 

We have tested the new software and firmware on the V3 Miniscope and everything seemed to run fine so likely you not being able to control the V3 LED is still a Linux issue.

**Comment by ximion** [comment]
> I'll test these changes out with a Miniscope connected to a Window's machine.

Yes, please - I was confident in the changes enough to open a PR, but wasn't able to test them at all. I'll play with this a bit more and next time upload a binary firmware blob to these changes so testing is easier for others.

> We have tested the new software and firmware on the V3 Miniscope and everything seemed to run fine so likely you not being able to control the V3 LED is still a Linux issue.

Yeah, that would be the most logical - since V3 was tested, and the firmware didn't actually change much, it's highly likely still some kind of communication issue. Your comments in the Qt software PR were very helpful, maybe I can figure out what's going on, I'll maybe have another go at this next week. Quite possibly the cause of this bug is something dumb, like another value sanitization somewhere or an endianess issue.
In any case, thanks a lot for your help and for permitting this work to happen in the first place by making all code available :-)

**Comment by ximion** [comment]
So, I couldn't resist playing around with the firmware a bit, just to get any reaction of the board (I can't connect a serial interface for debugging to it yet, unfortunately).
So, I wrote this function to set the LED brightness to a value directly:
```
static void tmp_send_ledpacket(uint8_t value)
{
	pendingI2CPacket[I2CPacketNextWriteIdx][0] = 0x98; // I2C address
	pendingI2CPacket[I2CPacketNextWriteIdx][1] = 0x03; // bytes in packet

	pendingI2CPacket[I2CPacketNextWriteIdx][2] = value;
	pendingI2CPacket[I2CPacketNextWriteIdx][3] = 0x00;

	pendingI2CPacket[I2CPacketNextWriteIdx][4] = 0x00;
	pendingI2CPacket[I2CPacketNextWriteIdx][5] = 0x00;

	I2CPacketNextWriteIdx = (I2CPacketNextWriteIdx + 1) % I2C_PACKET_BUFFER_SIZE;
	I2CNumPacketsPending++;
}
```
This should instantly switch the LED to a predefined value, but no matter whether I call this when a frame was acquired (in https://github.com/Aharoni-Lab/Miniscope-DAQ-Cypress-firmware/blob/master/Minisceop_DAQ/uvc.c#L520 apparently) or after a command was sent (https://github.com/Aharoni-Lab/Miniscope-DAQ-Cypress-firmware/blob/master/Minisceop_DAQ/uvc.c#L1341) the LED never changes brightness (I either set it to full brightness or none, so I should have noticed the difference easily). If I do force a `I2CProcessAndSendPendingPacket` call directly when the LED change command was created in the code which receives a new command from the computer, the device locks up and the kernel logs a -71 error when running SET_CUR (usually that is a read error, presumably the device doesn't react in time anymore).

@daharoni Do you maybe have an idea what is going on here? I would surely expect the device to change LED brightness if I instruct it to do so by directly adding the code for it to the firmware (there is no Linux-specific stuff involved here)...
Possible explanations might be miscompilation of the firmware (unlikely) a hardware defect (very unlikely), me not using the right I2C commands for the chip (possible) or the `I2CProcessAndSendPendingPacket` code not being run (since I get an image transmission I assume it is). I'll have another go at this later, maybe set up proper debugging (that should provide answers to what is happening way quicker).

**Comment by ximion** [comment]
I figured out the issue, I think. New PR for the changes in this one and a few related ones: https://github.com/Aharoni-Lab/Miniscope-DAQ-Cypress-firmware/pull/2

**Pull request closed without merging**
